/* XPM */
static char *misc_image[] = {
/* columns rows colors chars-per-pixel */
"80 60 240 2 ",
"   c #0B0B0B",
".  c #040103",
"X  c #131313",
"o  c #1C1C1C",
"O  c #100407",
"+  c #2E1014",
"@  c #150826",
"#  c #301629",
"$  c #3B1C21",
"%  c #301632",
"&  c #301935",
"*  c #301A3B",
"=  c #28102F",
"-  c #222222",
";  c #2B2B2B",
":  c #353535",
">  c #3C3C3C",
",  c #35273D",
"<  c #652E19",
"1  c #68311A",
"2  c #733618",
"3  c #451D2A",
"4  c #5B2C27",
"5  c #502E36",
"6  c #653426",
"7  c #603933",
"8  c #68363B",
"9  c #72372D",
"0  c #4F2314",
"q  c #77513F",
"w  c #301C44",
"e  c #51314A",
"r  c #623E43",
"t  c #623A52",
"y  c #542C51",
"u  c #444444",
"i  c #4C4C4C",
"p  c #545454",
"a  c #5B5B5B",
"s  c #5C5455",
"d  c #5D454E",
"f  c #624349",
"g  c #604A55",
"h  c #624957",
"j  c #79565B",
"k  c #714A4C",
"l  c #714663",
"z  c #6E5071",
"x  c #646464",
"c  c #6C6C6C",
"v  c #67636A",
"b  c #737373",
"n  c #7B7B7B",
"m  c #7B7474",
"M  c #726D6F",
"N  c #813B37",
"B  c #8E481B",
"V  c #A7541E",
"C  c #884A39",
"Z  c #945030",
"A  c #A75825",
"S  c #AC5834",
"D  c #99643D",
"F  c #B66734",
"G  c #D96D1E",
"H  c #C96829",
"J  c #D46C25",
"K  c #D6722B",
"L  c #D06F37",
"P  c #ED7C2A",
"I  c #ED7825",
"U  c #F17C33",
"Y  c #8C3F47",
"T  c #87584B",
"R  c #855855",
"E  c #914D4C",
"W  c #A8564D",
"Q  c #9F6842",
"!  c #9F7454",
"~  c #9D775D",
"^  c #8E6459",
"/  c #B87848",
"(  c #B3704C",
")  c #896668",
"_  c #9B7564",
"`  c #917772",
"'  c #A67862",
"]  c #875D61",
"[  c #D67744",
"{  c #C9734C",
"}  c #F27E47",
"|  c #E67945",
" . c #EA7D6D",
".. c #FE832B",
"X. c #FA832B",
"o. c #EA8133",
"O. c #FE8433",
"+. c #FE8A34",
"@. c #FE8D3C",
"#. c #F78539",
"$. c #FE913C",
"%. c #B88358",
"&. c #9F8167",
"*. c #9F866C",
"=. c #9E8877",
"-. c #8E827E",
";. c #BB9679",
":. c #AF886C",
">. c #BBA47E",
",. c #CC854B",
"<. c #D7884B",
"1. c #C9875A",
"2. c #D69258",
"3. c #FE8544",
"4. c #FE854B",
"5. c #FA8946",
"6. c #EC924B",
"7. c #FE9443",
"8. c #FF9C4C",
"9. c #F7954A",
"0. c #FE8652",
"q. c #FD855C",
"w. c #FB8657",
"e. c #E99755",
"r. c #F89C54",
"t. c #ED8055",
"y. c #FBA45B",
"u. c #F0A056",
"i. c #CC9969",
"p. c #C99978",
"a. c #CD8F69",
"s. c #FF896A",
"d. c #FD8668",
"f. c #E59E65",
"g. c #FF8A7B",
"h. c #FB8775",
"j. c #EB8272",
"k. c #DCA269",
"l. c #CAA678",
"z. c #D8A979",
"x. c #D6AE7A",
"c. c #EBAB6C",
"v. c #E9A569",
"b. c #FDAB64",
"n. c #F6AD6B",
"m. c #FAAC67",
"M. c #FEB16B",
"N. c #FBB56B",
"B. c #EBAC73",
"V. c #E5AC77",
"C. c #E9B279",
"Z. c #F5B475",
"A. c #FDB473",
"S. c #FEB975",
"D. c #FEBB7B",
"F. c #F7B87A",
"G. c #FEC17C",
"H. c #705389",
"J. c #99758B",
"K. c #CB7895",
"L. c #848484",
"P. c #8B8B8B",
"I. c #9B8887",
"U. c #939393",
"Y. c #9C9C9C",
"T. c #BA9888",
"R. c #A69895",
"E. c #B9A598",
"W. c #A39CA5",
"Q. c #A3A3A3",
"!. c #ABABAB",
"~. c #A8A4A5",
"^. c #B3B3B3",
"/. c #BBBBBB",
"(. c #B9B7B7",
"). c #B5A7A8",
"_. c #C9968A",
"`. c #FE8A88",
"'. c #FC8D9A",
"]. c #EB848A",
"[. c #CBAB85",
"{. c #CCB488",
"}. c #DAB485",
"|. c #CBB793",
" X c #D7B994",
".X c #E9BB87",
"XX c #FDBE81",
"oX c #F3BD82",
"OX c #E8BE93",
"+X c #FB8EA5",
"@X c #FE91A6",
"#X c #FC95B9",
"$X c #F089AD",
"%X c #CDB7A8",
"&X c #DFC39B",
"*X c #E9C38C",
"=X c #FEC484",
"-X c #FEC68B",
";X c #FECB8C",
":X c #F7C68A",
">X c #E8C699",
",X c #FDCC93",
"<X c #FACC98",
"1X c #FED294",
"2X c #FED39C",
"3X c #FAD79A",
"4X c #FED185",
"5X c #D9C9AE",
"6X c #E8CDA3",
"7X c #E4CAA5",
"8X c #FED6A4",
"9X c #FFDAA4",
"0X c #F6D9AA",
"qX c #FEDCAB",
"wX c #F5D5A6",
"eX c #F8DCB1",
"rX c #ECD3A9",
"tX c #FEE1AC",
"yX c #F8E1AA",
"uX c #FFE3B4",
"iX c #FDE6BA",
"pX c #FEEABC",
"aX c #F8E5B5",
"sX c #FC98CB",
"dX c #F699D7",
"fX c #EC91CE",
"gX c #F59CEB",
"hX c #F5A4F7",
"jX c #EDB0FA",
"kX c #CC91D6",
"lX c #C4C4C4",
"zX c #CCCCCC",
"xX c #D2D2D2",
"cX c #DBDBDB",
"vX c #FCEEC1",
"bX c #FFF6C5",
"nX c #E3E3E3",
"mX c #EBEBEB",
"MX c #F4F4F4",
"NX c #E9C3FB",
/* pixels */
"L.n b c c b n c L.L.L.L.b c b b b c c x c n L.P.L.U.n c c x c b b n n n n b b x b P.L.P.L.P.c p a p c L.x p b L.c n L.P.U.U.U.Y.Q.Q.!.^././.lXlX/.lXzXzXzXxXzXzX",
"L.L.L.b n L.L.n L.L.L.b v c v c c c x x x b L.P.L.L.P.b x x c b b n n n b b c n L.L.L.U.P.L.x a a a x x x x x c b n P.U.Y.Q.U.Y.Y.Q.^.^./././.lX/./.lXzXzXxXxXxX",
"L.P.L.n L.L.P.L.L.L.n c c M b n b x v x x c n P.P.L.P.L.c x c M b b b b b c c P.P.U.L.P.L.H.x a x x x c c b c b n P.P.P.P.U.Y.Q.Q.Q.^.^./././.^.^.^.^.lXzXzXzXxX",
"n L.P.L.n L.L.L.L.L.L.L.n n L.P.m x c x c c b n L.P.L.P.n -.c c c b b b b c c L.P.L.P.L.b x x a x x c b m b n n L.L.P.U.U.Y.Q.!.!.^.!.^.^.^.!.!.^.^.^./.zXzXzXxX",
"L.L.n L.L.P.P.L.` M o X o X - X                 o ;     - - X                 o X o o o                     X   o u a n Y.Q.Q.Q.!.!.!.!.~.!.!.^.^.^.^.lXzXzXzXzX",
"P.L.L.L.L.L.P.P.n   o # # & & # & & % # # # # # # # # & * * * w w w w w w w w * * & & & % % % * # ; & w w w w w & * , > a c U.Y.Q.Y.Q.Q.Q.Q.!.!.!.^./.lXzXlXzXzX",
"L.L.L.n b n L.L.L.- - 3 5 7 7 r 7 7 7 7 7 7 7 7 r f f f d s s s g g g g d d d d 7 f 7 f r f r r d g g g h h h h d d d e e i v L.Y.Q.Q.Q.~.!.!.!.!./.lXlXlXzXzXlX",
"n L.L.n b n L.L.P.X $ 7 q D D D F Q D Q D D ! ~ ~ ~ ~ &.*.=.*.&.*.&.&.&.&.~ ! ! ! ! ~ ! ! ! ' *.=.*.=.=.=.I.I.=._ ~ ~ ^ j h e v P.Y.Q.!.Q.Q.Q.!.^.lXlXlXlXlXzX/.",
"c c b b c b b n n   5 q D F ,.,.{ ,.,.,.2.i.i.i.l.l.x.x.x.x.l.i.l.l.[.l.i.a.2.i.i.i.i.i.l.[.{.[.{.{.|. X X|.|.|.{.l.i.>.;.*._ a v Y.!.^.!.Q.!.^./.lX/.lXlXlXlX/.",
"b c c c c c c b b   5 q %.,.2.e.e.e.e.B.C.V.B..XC.*X6X*X*Xc.c.v.B..XC.c.v.v.v.V.c.v.B.*XOXOXOX6X6X6X6X6X6X>X6X6X6X.X*X.Xx.x.l.:.) v (.^.^.!.^././././.lXlXlX/.^.",
"b c c c c c c c b   5 T ,.<.6.u.r.m.Z.XXF.F.oX:X3X3X:X:XZ.n.M.n.n.F.A.n.Z.A.F.A.Z.:X3X<X<XwX0X0X0XqX0XwX0X0X0X9X3X,X:X<X*X.Xx.x.;.) J.lX~.!.^.(./././.lXlX/.^.^.",
"b c c c c c c b b o , C / <.6.y.m.XXF.F.XX=X=X4X3X4X:XG.N.N.m.M.XX,XD.A.S.A.A.S.,X8X<X<X8XqXqXqX8X0X8XqXeXqX1X1X;X,X<X:X-X:X<X*X}.T.) W.^.Y.!.(././././.lX^.^.^.",
"b b c c c c c c b c Y.-.~ / 2.c.F.F.F.XXG.G.G.G.G.G.G.N.M.m.M.S.,X-X<XD.A.A.D.<X<X<X2X8X9X8XqX8X8XqXqXqX3X1X;X1X,X;X-X;X<X1X1X<X7X%X|.J.lXY.Q.!.^././././.!.^.^.",
"b c c c c c c b b L.P.!.lXlXE.;.a.k.V.F.G.N.N.b.N.G.G.b.b.m.M.-X-X,XXXA.A.S.<X<X<X2X9X2X=X=X2X8XqXqX2X,X;X;X1X=X-X;X,X1X2X1X3XqXaXeX%XR.^.^.!.^./.^././.!.!.^.!.",
"c c c b b c b b n L.L.P.P.L.~././.E.>.i.k.v.y.m.m.*XG.G.b.b.XX-XXX-XA.M.A.,X,X<X<X8X2XXXS.D.=X9X2X1X-X=X-X-X=X-X,X,X,X1X2X9XiXiXeXaXeX%XW.xX^.^.^.^./.!.!.!.!.^.",
"b c c n L.b b b n L.P.U.L.b b J.U.!.lX(.R.:.1.2.c.G.G.N.b.m.=XXX-XD.m.M.XX-X-X-X2X1XD.S.S.D.=X2X=X=X4X;X=X=X;X;X1X;X1X9XuXpXiXiXiXvXaX5X!.nX^.^././.!.!.!.!.^.!.",
"c c c n L.L.n n L.L.L.L.n L.L.P.Y.U.n L.Y./.lXE.T.l.z.f.r.n.XXM.M.A.b.S.-X-XS.S.-XS.S.A.S.=X9XtX;X=X=XXX=X;X;X;X1X1XuXiXuXuXiXiXvXvXvXrX).MX^.^.^.^.~.!.!.!.!.!.",
"c c b L.P.L.L.L.L.P.n n n L.Y.U.U.U.n n P.U.U.!.zXxX).p.1.k.B.v.n.XXb.XX-XD.M.S.;X=XM.S.;XtXtXtX2XG.=X-X-X;X;X1XqXuXuXuXuXiXpXpXvXvXeXeX%XMX!.^.!.~.Q.~.Q.!.!.!.",
"c c n P.L.L.L.L.P.n n L.n n U.U.U.U.L.b L.Y.Y.Y.U.P.Q./.zX).T.a.f.f.n.F.M.A.m.D.,XXXN.;X9XtX9X2X-X=X=X=X=X;X8XuXuXqXuXuXuXpXpXvXvXiXvXrX%XMX^.!.Q.Q.Q.Q.!.!././.",
"c b L.L.L.U.P.P.P.n n U.L.P.P.P.P.P.L.b n L.U.Y.U.P.P.P.P.n d L.R.T.a.2.f.Z.m.:XXXM.=X3X3X3X,X:XG.4X=X=X1X9XuXqXtXuXuXuXpXpXpXpXeXeXvXvX5XMX!.W.Y.Q.Q.Q.Y.^././.",
"c b n L.n L.n L.P.n n U.U.P.P.L.P.P.Y.P.b n U.P.P.P.U.U.L.X 5 q j J.L.-.T.a.k.B.n.Z.,X:XXX=XD.G.G.=X;X8XqXqXqXtXtXuXuXpXpXuXqXqXiXvXbXvX%XMXY.Y.Y.Y.Y.Q.!.^././.",
"b b n L.P.L.n L.n n L.U.P.P.L.L.P.P.P.L.H.L.n n b U.Y.U.n   4 2 9 N 8 k m L.P._.p.v.C.c.F.:XS.G.=X1X9XqX9XqXqXqXuXuXiXiXuX2X-X2XbXbXpXeX5XMXY.Y.Y.Q.Q.Y.!./.^./.",
"b n P.L.U.L.n b n n L.L.P.L.L.L.L.L.L.L.P.L.L.b n P.L.n b X 4 q W W Z E E r f c L.I.=.p..Xc.F.:X3X2X8X8XqXqXqXtXuXuXuX2X;X=X1X3XqXiXaXvX%XMXY.Y.Y.Y.Q.Q.^.^.^./.",
"n L.n L.P.n n L.P.L.b L.P.L.L.L.L.L.P.-.P.U.U.n b n b n n   4 Z S H L F S S C C 8 k s x m I.T.}.>X>X<X,X<XqXqXaXtX3X:X:X;X1X1X-X<XeXaXeX%XMXU.Y.Y.Y.Y.!.^.^.^.^.",
"n L.L.n n n n P.U.L.L.P.P.L.n n n n n L.P.U.U.n P.L.L.Y.U.  1 A H G J K [ H W S Z E N f d M Q.Q.R._._.z..X7X7X>XOXC..X.XOX.X.X.X.XOX7X7XT.MXY.Y.Y.Y.Y.!.!.^.^.^.",
"L.L.U.P.n n n P.U.P.L.P.L.n n n n n n L.P.L.n L.U.L.P.U.P.  6 A K [ U U  . .| J H F Q W R j Q.b P.).xXnXnXcXcXmXnXmXMXMXMXMXMXMXMXMXMXMXMX!.Q.!.Q.Y.Q.!.!.^.!.^.",
"L.P.P.n n n L.U.U.P.P.L.n n n n b n n n P.L.L.P.L.L.L.L.U.: 1 D L ].d. .fXgX .U o.<.,.1.' ) zXs         O O O X         X @ X o - ; - - u Y.Q.~.Q.Q.Q.!.!.^.^.^.",
"P.P.P.n n n L.P.P.L.L.L.n n n n n b n n L.n n n n n n P.U.- 6 A K t.#.`.`.`.0.} o.6.f.f.k.' zXO e e t l z z z h l l l l l l l z H.H.H.H.l nXW.Q.!.Y.U.Y.Y.!.!.^.",
"P.P.U.L.n n b L.P.P.L.L.n n b b b b b b b b b b b b L.P.L.  1 A K P U O.3.g.U O.q.9.m.v.V./ xX  r j ) _ =.=.=.~ ~ ~ _ _ ' ` I.I.U.I.I.I.m MXQ.Q.Q.U.Y.U.U.!.!.!.",
"U.U.P.L.n n L.L.P.P.L.L.n n n b b b b b b b b c b b L.P.L.- 1 D K P ....#.O.O.@.4.r.b.b.f.%.cX  j _ :.>.E.l.l.;.;.i.i.i.[.[.|.|.|.|.|.T.=.MXY.Q.U.U.U.U.Y.!.!.!.",
"U.P.n b n n L.P.U.P.L.L.n b b n b b b c c c c b c b b L.P.  1 A K P X.q.g.0.5.7.r.r.b.F.Z.a.xX  j *.>.{.x.V.k.V.k.c.x.&X&X5XrX7X>X&X&X XT.MXQ.Y.U.P.U.U.Y.!.Q.!.",
"n L.n n n n n n P.U.L.P.L.n b b b c b c c c c c c c b P.L.  6 A K o.X.+.h.@X7.8.r.b.M.b.y.' xX  R %.x.V.c.C.G.Z.F.*X3XwXaXyX0XrXwXwX6X>X_.MXY.U.U.U.U.U.Q.Q.Q.Q.",
"b n n n n n n n n L.L.P.n b b b b c c b x c c c c v b n M . < A K I X.X.0.@.7.8.y.y.y.b.Z.i.nX  R :.k.v.S.A.F.=X3X8XtXaXtXqXqX0X8X0X2XoXp.MXY.P.P.U.P.U.Y.Q.Q.Q.",
"n n n L.L.L.P.L.n n P.P.L.n b b b c c c c x c c x v x x x   < A G I +.+.@.$.9.8.y.N.G.G.F.%.cX  ] ;.x.n.Z.S.=X2X8XyXuXtXtXqX8X8XqX1X:XoXp.MXU.P.P.P.P.P.Q.Y.Q.Q.",
"n b n L.U.U.U.n n n L.L.P.n b b M b c c c c x x x x x x x   < V G P $.$.$.$.8.y.y.b.y.b.v./ xX  ] ;.k.c.A.-X3X9XtXuX3X2X8X8X8X8X-X=X=X:X_.MXP.P.P.U.U.U.Y.Y.Y.Q.",
"L.n n P.U.U.P.n n P.P.L.L.b b b c c c x c c x a x c x x a   < V K o.X.+.$.8.8.8.8.y.y.y.r.a.cX  R %.2.n.;X2X3XtXtX3X4XS.-X8X2X-X=X=X=X*X[.MXL.P.P.U.Y.Y.L.P.Y.Y.",
"P.L.L.U.U.U.U.L.n L.P.L.n b m b c c c x x c c x x x x x x   < V J P +.@.7.$.7.7.8.8.8.y.v.1.nX  R / k.oX<X3XyX3X,XXXF.A.XX,X=X=X=X=X1X:Xl.MXL.L.L.U.Y.U.L.L.U.Y.",
"L.U.U.U.U.P.P.L.L.n n L.P.n b c c b b c c x x c x x x x x   r V J P #.+.+.$.$.7.8.7.4.9.e.{ nX  T %.z..X:X=X1X;XS.A.A.A.,X8X=XF.:X;X:XF.p.MXL.L.P.U.U.U.L.L.P.Y.",
"n P.U.P.P.P.P.P.U.L.P.P.P.b b b c c c c x x x x x x x a x   8 V J o.X.O.O.+.+.$.$.+.4.U 5.{ xX- R ' i.C.B.c.B.C.f.c.c.OX>X>X>XoX.XC..XV.T.MXL.n L.U.U.U.L.n P.P.",
"n L.L.P.P.P.P.P.P.L.L.L.L.b b c c c x x x x x x c x x x a O 4 V G I X...q.0.q.+.+...4.'. .F xXM lXcXcXcXcXnXmXnXnXnXMXMXMXMXMXmXmXMXMXMXMXY.L.n J.L.P.P.n L.L.n ",
"n n n P.P.L.P.L.L.L.n n n b b b c b c c c x x c x x v x a   < V J P X...s.dX@Xq.....O.q.6.L c       - b n n L.n m J.L.L.L.L.n n n n L.P.L.n n P.P.n n P.n n L.b ",
"n n n P.P.P.L.L.L.n n b n b b b b c c c c x x x x x x x x   < V J I ..U 4.`.`.O...I 0.d.o.{ E e e e e xXH.L.n n n n L.L.L.L.n n n L.P.P.L.n n L.P.n b L.n b b x ",
"L.n n L.P.P.L.L.L.n n n n b b b c c c c c x x x x x x x c   < A L t.'.q.3.d.g.U ....$.@.$.<.( T k q 7 mXL.n n n b b L.L.L.n b b n n P.P.L.n b L.P.L.b b b c x c ",
"P.P.U.U.P.P.P.L.L.L.n b b b n b b c c c c x x x x x v v a . 6 A [ $XhXg.4.@.O.....+.+.$.$.6.<.{ / ( D mXn L.b b b b n L.n n b b b L.L.L.n b b n L.n b b x p p n ",
"L.P.U.U.U.P.L.P.L.L.n L.n b n b b b b c c c x x v x p ; . @ 6 S [  .+Xg.} U O.......+.$.7.9.6.e.2.,.( nXn b b b c n n L.n b b b b L.L.L.n b b n b b b x p b n P.",
"n n L.n P.P.L.P.L.L.n n n n n n L.P.n b c x x x a ; . @ = y 9 S K.fX`. .s.`.4.U 0.....+.+.5.9.9.e.6.,.nXb b c b b n n n b b b L.n b b L.n c n n b c c x p L.Y.P.",
"b n n n L.n n n P.P.L.n L.n L.L.P.L.L.L.M c a ; . O = w 3 r E { $XgXfXdX#XgX`.4.#X`.....O.0.$.7.9.e.,.nXb c c c b n n n b c n n n c b n n b c n n c x a a b U.L.",
"L.L.n n n n b L.L.L.P.L.L.L.P.L.n U.P.n M c ; . + + 3 4 9 W K.K.$XjXjXhX#X'.s.g.dXg.+...4.`.g.5.7.9.[ cXc c b b b n n b c c n n n c c n n c x b c c x a u u L.P.",
"L.n b n n P.L.n L.P.P.L.L.L.P.n n L.L.n b c   + + 0 2 B S K.kXfXdXjXNXjXsXs.0.d.s.O.O.O.@.'.#X5.+.9.[ zXc c n b c c n c c c n n b c c b b c x b x a x p u c Y.U.",
"P.L.n n L.U.P.P.U.P.P.L.P.P.P.U.L.L.P.n b n   $ 2 B V H H  .K.+XhXhXjXgXgX#X0.O.O.U O.U g.s.5.s.3.#.,.lXx b b b x b b c c b c c b x b x b c x b c a a a u i b n ",
"L.n b n n P.U.U.U.U.P.P.P.P.P.U.n n P.L.L.L.o 0 B V H J U } w.h.'.dXhX#X#X#X0.O.......#.'.s...+.+.@.L lXc c b c x c b x c b x c c x c x c x a x c x p p i > : > ",
"L.L.n n b L.U.U.U.U.U.L.L.U.U.Y.U.n L.P.P.L.o < B H K I U } w.`.+X#XsXg.h.h.g.s...U ....@.O...+.@.7.L zXc x c x c c c x x x x x x x a a x x a x p x a i u u : : ",
"L.L.n b n n P.P.n L.L.n P.U.P.U.U.n L.U.U.L.  1 V J } } 0.0.w.+XgX`.d.4.g.sXhXg.........X.+.+...+.o.L lXv x x x x x x x x a a a p i a p p a a x p p p p i > : : ",
"n L.b b n n L.L.n b n n L.n n L.P.L.n Y.U.n - 1 A J K.dXd.d.d.@XhX#X4.5.w.`.#Xs.......+.+.+.$.+.X.X.L 5Xx a a p a a a a x a p x b c P.x i p p a i p i u u > : > ",
"n L.L.n b n n b n n n b n n n n n n n U.n n > 1 V H  .fX .} } t.h.} #.U | } t.U P P X.X.o.#.o.#.o.o.H (.a p c b n a p a p i p L.U.P.b u i p i a i p p u > : p i ",
"b n L.b b n n L.L.n n n b n L.L.b m n n n P.P.cXMXMXMXMXMXmX%XlX/././.lX^.^.5XlX(.(./.^.^.!.^./.^.!.^.c p x L.P.n i i p i p c P.U.P.c u u u i p i u u u : u P.n ",
"n n L.L.L.L.L.L.n n L.L.L.P.P.L.n b n n P.U.P.P.L.n n P.P.L.n v x x x x a x x x a x a a b c b L.x p a p p b P.P.c a i i i c U.L.P.c i u u u u i u i u : > p P.U.",
"b L.n n n n b n n n P.U.U.U.U.n n n P.U.Y.U.P.U.P.n U.P.L.L.P.b x x x a x x a x a x x c L.P.P.n x a p a a L.P.L.L.n b a p x U.L.U.n a i u u > i > > > > u L.Y.U.",
"L.L.n c n n n b n n L.U.Y.U.U.L.n n L.U.U.U.P.n n L.P.L.L.n b c x x x x x x a x x a x L.P.L.P.n x a a a x b P.L.L.U.P.x a c P.P.L.U.L.L.x u > > > > > : i L.U.U.",
"L.L.b n n n n n b n P.U.U.U.U.L.b n n L.n L.n n b L.P.n b c v x x x a x x x a x a x c b L.U.P.n c b n b x c L.Y.n L.P.n c c L.Q.L.L.P.U.P.n i > > > > > a P.Y.P."
};
