master:
  push:
    - stages:
        - name: build
          image: ubuntu:latest
          script:
            - apt update && apt install -y mingw-w64 g++-mingw-w64-x86-64 nasm make perl gcc g++ zip
            # - make mingwcc -j$(nproc) RELEASEBUILD=1
            # - zip fbneo.zip fbneo.exe
            - make mingwcc64 -j$(nproc) RELEASEBUILD=1
            - zip fbneo64.zip fbneo64.exe

        - name: upload_release
          image: cnbcool/attachments:latest
          settings:
            attachments:
              # - fbneo.zip
              - fbneo64.zip
