// pce-cd game detection via SHA1 of toc(toc-hash)  -dink 2026

// Please help us populate this list!
// ---
// Using [DEBUG] FBNeo, Watch for the line "TOC Hash: ......" in the
// "debug console" (Misc -> Options -> Show debug console)
// Then add this string of hexidecimal bytes to the first column before
// the game in the list, below.
// For example: b77b8776b62148a868ad9c0cbe8c7bd9a8ab69fb for Gate of Thunder

// If you find the same Game with a different hash, just duplicate the entire
// line, and change the hash on the new one.

// If you still want to help, but don't want to bother with this source code stuff,
// Just paste the hash(es) & game name(s) to a github issue, or PM me
// on the neo-source forum.  thanks! :)

struct pce_cd_dink {
	TCHAR *sha1;
	TCHAR *name;
	TCHAR *id;
	TCHAR *year;
	TCHAR *company;
};

static pce_cd_dink pcengine_cd_games[] = {
	{ _T(""), _T("3x3 Eyes Sanjiyan Hensei"), _T("3x3eyes"), _T("1994"), _T("NEC Home Electronics") },
	{ _T(""), _T("A. III"), _T("a3"), _T("1993"), _T("Artdink") },
	{ _T(""), _T("The Addams Family"), _T("addamsfamily"), _T("1991"), _T("ICOM Simulations / NEC") },
	{ _T(""), _T("Advanced V.G."), _T("advancedvg"), _T("1994"), _T("TGL") },
	{ _T(""), _T("Adventure Quiz Capcom World Hatena no Dai Bouken"), _T("adventurequiz"), _T("1992"), _T("Capcom / Hudson") },
	{ _T(""), _T("Ai Cho Aniki"), _T("aichoaniki"), _T("1995"), _T("Masaya") },
	{ _T(""), _T("Akiyamajin no Suugaku Misuteri - Hihou Indo no Honoo wo Sisyu Seyo"), _T("akiyamajin"), _T("1994"), _T("NHK") },
	{ _T(""), _T("Alzadick: Summer Carnival '92"), _T("alzadick"), _T("1992"), _T("Naxat") },
	{ _T(""), _T("Ane-san"), _T("anesan"), _T("1995"), _T("NEC") },
	{ _T(""), _T("Aoki Ookami to Shiroki Mejika: Genchou Hishi"), _T("aokiookami"), _T("1993"), _T("Koei") },
	{ _T(""), _T("Arunamu no Kiba"), _T("arunamukiba"), _T("1994"), _T("Right Stuff") },
	{ _T(""), _T("Asuka 120% Maxima BURNING Fest."), _T("asuka120"), _T("1995"), _T("Fill-in-Cafe / NEC Avenue") },
	{ _T(""), _T("The Atlas: Renaissance Voyager"), _T("atlas"), _T("1994"), _T("Artdink") },
	{ _T(""), _T("Aurora Quest Otaku no Seiza"), _T("auroraquest"), _T("1993"), _T("Pack-In-Video") },
	{ _T(""), _T("Auto Crusher Palladium"), _T("autocrusher"), _T("1994"), _T("Pack-In-Video") },
	{ _T(""), _T("Avenger"), _T("avenger"), _T("1990"), _T("Telenet Japan / Laser Soft") },
	{ _T(""), _T("Babel"), _T("babel"), _T("1992"), _T("Telenet Japan") },
	{ _T(""), _T("Baby Jo the Super Hero"), _T("babyjo"), _T("1992"), _T("Microworld") },
	{ _T(""), _T("Bakuden Unbalanced Zone"), _T("bakuden"), _T("1994"), _T("Sony Music Entertainment") },
	{ _T(""), _T("Bakuretsu Hunter Duo Comic"), _T("bakuretsuhunter"), _T("1994"), _T("") },
	{ _T(""), _T("Bakushou Yoshimoto No Shinkigeki"), _T("bakushouyoshi"), _T("1994"), _T("Hudson") },
	{ _T(""), _T("Bastard!!"), _T("bastard"), _T(""), _T("") },
	{ _T(""), _T("Basted"), _T("basted"), _T("1994"), _T("NEC Avenue") },
	{ _T(""), _T("Battlefield '94 In Super Battle Dream"), _T("battlefield94"), _T("1994"), _T("Fujicom") },
	{ _T(""), _T("Bazaru de Gozaru no Game Degozaru"), _T("bazaru"), _T("1996"), _T("NEC Home Electronics") },
	{ _T(""), _T("Beyond Shadowgate"), _T("beyondshadowgate"), _T("1993"), _T("ICOM Simulations") },
	{ _T(""), _T("Bikini Girls"), _T("bikinigirls"), _T(""), _T("Excite Software") },
	{ _T(""), _T("Bikkuriman Daijikai"), _T("bikkuriman"), _T("1988"), _T("Hudson") },
	{ _T(""), _T("Bishojyo Jyanshi Idol Pai"), _T("idolpai"), _T("1995"), _T("Hacker International") },
	{ _T(""), _T("Bishoujo Senshi Sailor Moon"), _T("sailormoon"), _T("1994"), _T("Banpresto") },
	{ _T(""), _T("Bishoujo Senshi Sailor Moon Collection"), _T("sailormooncol"), _T("1994"), _T("Banpresto") },
	{ _T("79f0ba17ffdaf97f7e45bcca6b9f77462c126977"), _T("Black Hole Assault"), _T("blackholeassault"), _T("1993"), _T("Micronet") },
	{ _T("42162eb4007bedfc85cf1ccef5f4d353a1a8d730"), _T("Blood Gear"), _T("bloodgear"), _T("1994"), _T("Hudson") },
	{ _T(""), _T("Bomberman '94 Taikenban"), _T("bomberman94demo"), _T("1993"), _T("Hudson") },
	{ _T(""), _T("Bonanza Bros."), _T("bonanzabros"), _T("1992"), _T("NEC Avenue") },
	{ _T(""), _T("Bonk 3: Bonk's Big Adventure CD"), _T("bonk3cd"), _T("1993"), _T("Hudson") },
	{ _T(""), _T("Brandish"), _T("brandish"), _T("1994"), _T("Falcom / NEC Home Electronics") },
	{ _T(""), _T("Browning"), _T("browning"), _T("1992"), _T("Telenet Japan") },
	{ _T(""), _T("Builderland"), _T("builderland"), _T("1992"), _T("Microworld") },
	{ _T(""), _T("Burai: Hachigyoku no Yuushi Densetsu"), _T("burai"), _T("1991"), _T("Riverhillsoft") },
	{ _T(""), _T("Burai II: Yami Koutei no Gyakushuu"), _T("burai2"), _T("1992"), _T("Riverhillsoft") },
	{ _T(""), _T("Buster Bros. (Pomping World in Japan)"), _T("busterbros"), _T("1991"), _T("Hudson") },

	{ _T(""), _T("CAL II"), _T("cal2"), _T("1993"), _T("NEC Avenue") },
	{ _T(""), _T("CAL III"), _T("cal3"), _T("1994"), _T("NEC Avenue") },
	{ _T(""), _T("Camp California"), _T("campcalifornia"), _T("1993"), _T("NEC") },
	{ _T(""), _T("Cardangels"), _T("cardangels"), _T("1994"), _T("Fujicom") },
	{ _T("36b0631c09fb9d2b2b9959aa45dd08278cac3624"), _T("Castlevania: Rondo of Blood"), _T("cvaniarondo"), _T("1993"), _T("Konami") },
	{ _T(""), _T("CD Battle Hikari no Yuushatachi"), _T("cdbattle"), _T("1993"), _T("King Records") },
	{ _T(""), _T("CD Bishojyo Pachinko 4 Sisters"), _T("cdpachinko4"), _T("1995"), _T("Hacker International") },
	{ _T(""), _T("CD Hanafuda Bishojuo Gambler"), _T("cdhanafuda"), _T("1994"), _T("Hacker International") },
	{ _T(""), _T("CD Mahjong Bishoujo Tyuushinha"), _T("cdmahjong"), _T("1993"), _T("Hacker International") },
	{ _T(""), _T("CD Pachisuro Bishojuo Gambler"), _T("cdpachisuro"), _T("1994"), _T("Hacker International") },
	{ _T(""), _T("Championship Rally"), _T("championshiprally"), _T("1993"), _T("Intec") },
	{ _T(""), _T("Chiki Chiki Boys"), _T("chikichikiboys"), _T("1994"), _T("NEC Avenue") },
	{ _T(""), _T("Cho Aniki"), _T("choaniki"), _T("1992"), _T("Masaya") },
	{ _T(""), _T("Cobra"), _T("cobra"), _T("1989"), _T("Hudson") },
	{ _T(""), _T("Cobra II"), _T("cobra2"), _T("1991"), _T("Hudson") },
	{ _T(""), _T("Color Wars"), _T("colorwars"), _T("1992"), _T("Coconuts Japan") },
	{ _T(""), _T("Conan"), _T("conan"), _T(""), _T("") },
	{ _T(""), _T("Cosmic Fantasy: Bouken Shounen Yuu"), _T("cosmicfantasy"), _T("1990"), _T("Laser Soft") },
	{ _T(""), _T("Cosmic Fantasy 2"), _T("cosmicfantasy2"), _T("1991"), _T("Laser Soft") },
	{ _T(""), _T("Cosmic Fantasy 3: Bouken Shounen Rei"), _T("cosmicfantasy3"), _T("1992"), _T("Laser Soft") },
	{ _T(""), _T("Cosmic Fantasy 4: Ginga Shounen Densetsu - Totsunyuu-hen"), _T("cosmicfantasy4a"), _T("1994"), _T("Telenet Japan") },
	{ _T(""), _T("Cosmic Fantasy 4: Ginga Shounen Densetsu - Gekitou-hen"), _T("cosmicfantasy4b"), _T("1994"), _T("Telenet Japan") },
	{ _T(""), _T("Cosmic Fantasy Visual Collection Vol. 1"), _T("cosmicvisual1"), _T("1993"), _T("Telenet Japan") },
	{ _T("0b4e27c66b0e9afc8a033306efed80d6893e6e7a"), _T("Cotton: Fantastic Night Dreams"), _T("cotton"), _T("1993"), _T("Hudson") },
	{ _T(""), _T("Crazy Hospital: Fushigi no Kuni no Tenshi"), _T("crazyhospital"), _T("1997"), _T("") },
	{ _T(""), _T("Crest of Wolf"), _T("crestofwolf"), _T("1993"), _T("Hudson") },
	{ _T(""), _T("Cyber City Oedo 808"), _T("cybercityoedo"), _T("1991"), _T("Masaya") },

	{ _T(""), _T("Daisenpuu Custom"), _T("daisenpuucustom"), _T("1991"), _T("NEC Avenue") },
	{ _T(""), _T("Daisenryaku II: Campaign Version"), _T("daisenryaku2"), _T("1992"), _T("Micro Cabin") },
	{ _T(""), _T("The Davis Cup Tennis"), _T("daviscup"), _T("1992"), _T("Microworld") },
	{ _T(""), _T("De Ja"), _T("deja"), _T("1996"), _T("NEC Interchannel") },
	{ _T(""), _T("Dead Of The Brain 1 & 2"), _T("deadofthebrain"), _T("1999"), _T("NEC Home Electronics") },
	{ _T(""), _T("Death Bringer - The Knight Of Darkness"), _T("deathbringer"), _T("1990"), _T("Telenet Japan") },
	{ _T(""), _T("Deden no Den"), _T("dedenonden"), _T("1994"), _T("Hudson") },
	{ _T(""), _T("Dekoboko Densetsu Hashiru Wagamanma"), _T("dekoboko"), _T("1990"), _T("Telenet Japan") },
	{ _T(""), _T("Dennou Tenshi: Digital Angel"), _T("digitalangel"), _T("1994"), _T("Tokuma Shoten Intermedia") },
	{ _T(""), _T("Develo Magazine Vol. 1"), _T("develomag1"), _T("1996"), _T("NEC") },
	{ _T(""), _T("Develo Starter Kit: Assembler"), _T("develoasm"), _T("1996"), _T("NEC") },
	{ _T(""), _T("Develo Starter Kit: BASIC"), _T("develobasic"), _T("1996"), _T("NEC") },
	{ _T(""), _T("Doraemon Nobita no Dorabian Night"), _T("doraemon"), _T("1992"), _T("Hudson") },
	{ _T(""), _T("Double Dragon II: The Revenge"), _T("doubledragon2"), _T("1993"), _T("Naxat") },
	{ _T(""), _T("Doukyuusei"), _T("doukyuusei"), _T("1995"), _T("NEC Avenue") },
	{ _T(""), _T("Download 2"), _T("download2"), _T("1991"), _T("NEC Avenue") },
	{ _T(""), _T("Downtown Nekketsu Monogatari"), _T("downtownnekke"), _T("1993"), _T("Naxat") },
	{ _T(""), _T("Downtown Nekketsu Koushinkyoku: Soreyuke Daiundoukai"), _T("downtownundokai"), _T("1992"), _T("Naxat") },
	{ _T(""), _T("Dragon Ball Z: Idainaru Son Goku Densetsu"), _T("dragonballz"), _T("1994"), _T("Bandai") },
	{ _T(""), _T("Dragon Half"), _T("dragonhalf"), _T("1994"), _T("Micro Cabin") },
	{ _T(""), _T("Dragon Knight & Grafitti"), _T("dragonknightgra"), _T("1995"), _T("NEC Avenue") },
	{ _T(""), _T("Dragon Knight II"), _T("dragonknight2"), _T("1992"), _T("NEC Avenue") },
	{ _T(""), _T("Dragon Knight III"), _T("dragonknight3"), _T("1994"), _T("NEC Avenue") },
	{ _T(""), _T("Dragon Slayer: The Legend of Heroes"), _T("dragonslayer1"), _T("1991"), _T("Hudson") },
	{ _T(""), _T("Dragon Slayer: The Legend of Heroes II"), _T("dragonslayer2"), _T("1992"), _T("Hudson") },
	{ _T(""), _T("Dungeon Explorer II"), _T("dungeonexplorer2"), _T("1993"), _T("Hudson") },
	{ _T(""), _T("Dungeon Master: Theron's Quest"), _T("dungeonmaster"), _T("1992"), _T("Victor") },
	{ _T(""), _T("The Dynastic Hero"), _T("dynastichero"), _T("1994"), _T("Hudson") },

	{ _T(""), _T("Efera & Jiliora: The Emblem From Darkness"), _T("eferajiliora"), _T("1991"), _T("Brain Grey") },
	{ _T(""), _T("Eikan Wa Kimini"), _T("eikanwakimini"), _T("1994"), _T("Artdink") },
	{ _T(""), _T("Eiyuu Sankokushi"), _T("eiyuusankoku"), _T("1993"), _T("Irem") },
	{ _T(""), _T("Emerald Dragon"), _T("emeralddragon"), _T("1994"), _T("NEC Home Electronics") },
	{ _T(""), _T("Emerald Dragon Taikenban + Guidebook"), _T("emeralddemo"), _T(""), _T("") },
	{ _T(""), _T("Exile"), _T("exile"), _T("1991"), _T("Telenet Japan") },
	{ _T(""), _T("Exile: Wicked Phenomenon"), _T("exilewicked"), _T("1992"), _T("Telenet Japan") },

	{ _T(""), _T("F1 Circus Special"), _T("f1circusspecial"), _T("1992"), _T("Nihon Bussan") },
	{ _T(""), _T("F1 Team Simulation Project F"), _T("projectf"), _T("1992"), _T("Telenet Japan") },
	{ _T(""), _T("Faceball"), _T("faceball"), _T("1994"), _T("Riverhillsoft") },
	{ _T(""), _T("Faerie Dust Story: Meikyuu no Elfeene"), _T("faeriedust"), _T("1990"), _T("Shin-Nihon Laser Soft") },
	{ _T(""), _T("Farjius no Jakoutei: Neo Metal Fantasy"), _T("farjius"), _T("1994"), _T("Naxat") },
	{ _T(""), _T("Faussete Amour"), _T("fausseteamour"), _T("1993"), _T("Naxat") },
	{ _T(""), _T("Fiend Hunter"), _T("fiendhunter"), _T("1993"), _T("Right Stuff") },
	{ _T(""), _T("Fighting Street (Street Fighter)"), _T("fightingstreet"), _T("1988"), _T("Hudson") },
	{ _T(""), _T("Final Zone II"), _T("finalzone2"), _T("1990"), _T("Telenet Japan") },
	{ _T(""), _T("Fire Pro Joshi: Doumu Choujo Taisen Zenjo vs JWP"), _T("fireprojoshi"), _T("1995"), _T("Human") },
	{ _T(""), _T("Flash Hiders"), _T("flashhiders"), _T("1993"), _T("Right Stuff") },
	{ _T(""), _T("Forgotten Worlds"), _T("forgottenworlds"), _T("1992"), _T("NEC Avenue") },
	{ _T(""), _T("Formation Soccer '95"), _T("formationsoccer95"), _T("1995"), _T("Human") },
	{ _T(""), _T("Fray CD: Xak Gaiden"), _T("fraycd"), _T("1994"), _T("Micro Cabin") },
	{ _T(""), _T("Fushigi no Umi no Nadia: The Secret of Blue Water"), _T("nadia"), _T("1993"), _T("Hudson") },

	{ _T(""), _T("Gain Ground SX"), _T("gaingroundsx"), _T("1992"), _T("NEC Avenue") },
	{ _T(""), _T("Galaxy Deka Gayvan"), _T("gayvan"), _T("1993"), _T("Intec") },
	{ _T(""), _T("Galaxy Freulein Yuna"), _T("galaxyyuna"), _T("1992"), _T("Hudson") },
	{ _T(""), _T("Galaxy Freulein Yuna II: Eternal Princess"), _T("galaxyyuna2"), _T("1995"), _T("Hudson") },
	{ _T(""), _T("Galaxy Freulein Yuna HuVideo CD"), _T("yunahuvideo"), _T("1993"), _T("Hudson") },
	{ _T(""), _T("Gambler Jikochuushinha"), _T("gamblerjiko"), _T("1989"), _T("Hudson") },
	{ _T(""), _T("Gambler Jikochuushinha Mahjong Puzzle Collection"), _T("gamblermahjong"), _T("1992"), _T("Hudson") },
	{ _T(""), _T("Garou Densetsu 2"), _T("fatalfury2"), _T("1994"), _T("Hudson") },
	{ _T(""), _T("Garou Densetsu Special"), _T("fatalfuryspecial"), _T("1994"), _T("Hudson") },
	{ _T("b77b8776b62148a868ad9c0cbe8c7bd9a8ab69fb"), _T("Gate of Thunder"), _T("gateofthunder"), _T("1992"), _T("Hudson") },
	{ _T("a64245a727107ffce09c77235da446b709de9975"), _T("Gate of Thunder, Bonk's Adventure, Bonk's Revenge"), _T("gotbonkmulti"), _T("1992"), _T("Hudson") },
	{ _T(""), _T("Genocide"), _T("genocide"), _T("1992"), _T("Brain Grey") },
	{ _T(""), _T("Gensou Tairiku Auleria"), _T("auleria"), _T("1993"), _T("Taito") },
	{ _T(""), _T("Ghost Sweeper Mikami"), _T("ghostsweeper"), _T("1994"), _T("Banpresto") },
	{ _T("5d09158ae6a40aa82ffe4cd390d813f372799357"), _T("Ginga Fukei Densetsu Sapphire"), _T("sapphire"), _T("1995"), _T("Hudson") },
	{ _T(""), _T("Go! Go! Birdie Chance"), _T("gogobirdie"), _T("1995"), _T("NEC") },
	{ _T(""), _T("God Panic Shijyou Saikyu Gundan"), _T("godpanic"), _T("1992"), _T("Teichiku") },
	{ _T(""), _T("Godzilla"), _T("godzilla"), _T("1993"), _T("Turbo Technologies") },
	{ _T(""), _T("Golden Axe"), _T("goldenaxe"), _T("1990"), _T("Telenet Japan") },
	{ _T(""), _T("Gotzendiener"), _T("gotzendiener"), _T("1994"), _T("Gainax") },
	{ _T("7c0714f9017dd18f61967c02de252d0c0ae55ae6"), _T("Gradius II: Gofer no Yabou"), _T("gradius2"), _T("1992"), _T("Konami") },

	{ _T(""), _T("Hatsukoi Monogatari"), _T("hatsukoi"), _T("1994"), _T("Tokuma Shoten Intermedia") },
	{ _T(""), _T("Hawaiian Island Girls"), _T("hawaiiangirls"), _T(""), _T("Games Express") },
	{ _T(""), _T("Hawk F-123"), _T("hawkf123"), _T("1992"), _T("Pack-In-Video") },
	{ _T(""), _T("Hellfire S"), _T("hellfires"), _T("1991"), _T("NEC Avenue") },
	{ _T(""), _T("Hi-Leg Fantasy"), _T("hilegfantasy"), _T("1994"), _T("Games Express") },
	{ _T(""), _T("High Grenadier"), _T("highgrenadier"), _T("1991"), _T("Telenet Japan") },
	{ _T(""), _T("Hihou Densetsu Kris no Bouken"), _T("krisnobouken"), _T("1990"), _T("Pack-In-Video") },
	{ _T(""), _T("Himitsu no Hanazono"), _T("himitsuhanazono"), _T("1993"), _T("NEC") },
	{ _T(""), _T("Horror Story"), _T("horrorstory"), _T("1993"), _T("NEC Avenue") },
	{ _T(""), _T("Human Sports Festival"), _T("humansports"), _T("1992"), _T("Human") },
	{ _T(""), _T("Hyaku Monogatari"), _T("hyakumonogatari"), _T("1995"), _T("Hudson") },
	{ _T(""), _T("Hyper Wars"), _T("hyperwars"), _T("1994"), _T("Hudson") },

	{ _T(""), _T("Iga Ninden Gaou"), _T("iganinden"), _T("1993"), _T("Nichibutsu") },
	{ _T(""), _T("Image Fight II"), _T("imagefight2"), _T("1992"), _T("Irem") },
	{ _T(""), _T("Implode"), _T("implode"), _T("1991"), _T("NEC") },
	{ _T(""), _T("Inoue Mami: Kono Hoshi Ni Tatta Hitori no Kimi"), _T("inouemami"), _T("1992"), _T("Hudson") },
	{ _T(""), _T("IQ PANIC"), _T("iqpanic"), _T("1992"), _T("IGS") },
	{ _T(""), _T("It Came From the Desert"), _T("itcamefromdesert"), _T("1991"), _T("Cinemaware / NEC") },

	{ _T(""), _T("J Thunder"), _T("jthunder"), _T("1993"), _T("NEC") },
	{ _T(""), _T("J. B. Harold Murder Club"), _T("jbharold"), _T("1990"), _T("Hudson") },
	{ _T(""), _T("J. League Tremendous Soccer '94"), _T("jleague94"), _T("1994"), _T("NEC") },
	{ _T(""), _T("Jack Nicklaus Turbo Golf"), _T("jacknicklaus"), _T("1990"), _T("Accolade") },
	{ _T(""), _T("Jack Nicklaus World Tour Golf"), _T("jacknicklauswt"), _T("1993"), _T("Accolade") },
	{ _T(""), _T("Jantei Monogatari"), _T("jantei"), _T("1990"), _T("Telenet Japan") },
	{ _T(""), _T("Jantei Monogatari 2: Uchuu Tantei Diban - Shutsudou Hen"), _T("jantei2a"), _T("1991"), _T("Atlus") },
	{ _T(""), _T("Jantei Monogatari 2: Uchuu Tantei Diban - Kanketsu Hen"), _T("jantei2b"), _T("1992"), _T("Atlus") },
	{ _T(""), _T("Jantei Monogatari 3: Saber Angel"), _T("jantei3"), _T("1993"), _T("Atlus") },
	{ _T(""), _T("Jim Power"), _T("jimpower"), _T("1992"), _T("NEC") },
	{ _T(""), _T("John Madden Duo CD Football"), _T("maddenduo"), _T("1993"), _T("Electronic Arts") },
	{ _T(""), _T("Jong Shin Densetsu"), _T("jongshin"), _T("1995"), _T("NEC") },
	{ _T(""), _T("Juuoki (Altered Beast)"), _T("alteredbeast"), _T("1990"), _T("NEC Avenue") },

	{ _T(""), _T("Kabuki Itouryodan"), _T("kabuki"), _T("1995"), _T("Hudson") },
	{ _T(""), _T("Kagamai no Kuni no Legend"), _T("kagaminokuni"), _T("1989"), _T("Victor") },
	{ _T(""), _T("Kaizou Choujin Shubibinman 3: Ikai no Princess"), _T("shubibinman3"), _T("1992"), _T("Masaya") },
	{ _T(""), _T("Kakutou Haou Densetsu Algunos"), _T("algunos"), _T("1993"), _T("Intec") },
	{ _T(""), _T("Kawa no Nushizuri Shizenha"), _T("nushizuri"), _T("1992"), _T("Pack-In-Video") },
	{ _T(""), _T("Kaze Kiri Ninja Action"), _T("kazekiri"), _T("1994"), _T("Naxat") },
	{ _T(""), _T("Kaze no Densetsu Xanadu"), _T("xanadu"), _T("1994"), _T("Falcom / Hudson") },
	{ _T(""), _T("Kaze no Densetsu Xanadu II"), _T("xanadu2"), _T("1995"), _T("Falcom / Hudson") },
	{ _T(""), _T("Kaze no Densetsu Xanadu Taikenban + Guidebook"), _T("xanadudemo"), _T(""), _T("Falcom / Hudson") },
	{ _T(""), _T("Kiaidan 00"), _T("kiaidan00"), _T("1992"), _T("Telenet Japan") },
	{ _T(""), _T("The Kick Boxing"), _T("kickboxing"), _T("1992"), _T("Microworld") },
	{ _T(""), _T("Kidou Keisatsu Patlabor-Griffon"), _T("patlabor"), _T("1993"), _T("Riverhillsoft") },
	{ _T(""), _T("Kisou Louga"), _T("kisoulouga"), _T("1993"), _T("Kogado") },
	{ _T(""), _T("Kisou Louga II: The Ends of Shangrila"), _T("kisoulouga2"), _T("1995"), _T("Kogado") },
	{ _T(""), _T("KO Sekai Beast San Senshi Gaia Fukkatsu Fin."), _T("beastsanjuushi"), _T("1994"), _T("Pack-In-Video") },
	{ _T(""), _T("Kuusou Kagaku Sekai Gulliver Boy"), _T("gulliverboy"), _T("1995"), _T("Hudson") },

	{ _T(""), _T("Lady Phantom"), _T("ladyphantom"), _T("1991"), _T("Laser Soft") },
	{ _T(""), _T("Langrisser: Hikari no Matsuei"), _T("langrisser"), _T("1993"), _T("Masaya") },
	{ _T(""), _T("Laplace no Ma"), _T("laplace"), _T("1992"), _T("Human") },
	{ _T(""), _T("Last Alert (Red Alert)"), _T("lastalert"), _T("1990"), _T("NEC") },
	{ _T("ea568184145b85eea5ac0dba145ac6f85170328f"), _T("Last Armageddon"), _T("larmageddon"), _T("1990"), _T("Brain Grey") },
	{ _T(""), _T("Legion"), _T("legion"), _T("1990"), _T("Telenet Japan") },
	{ _T(""), _T("Lemmings"), _T("lemmings"), _T("1992"), _T("Sunsoft") },
	{ _T(""), _T("Linda Cube"), _T("lindacube"), _T("1995"), _T("NEC") },
	{ _T(""), _T("The Local Girls of Hawaii"), _T("localgirlshawaii"), _T(""), _T("Games Express") },
	{ _T(""), _T("Lodoss Tousenki (Record of Lodoss War)"), _T("lodoss"), _T("1992"), _T("Hudson") },
	{ _T(""), _T("Lodoss Tousenki II"), _T("lodoss2"), _T("1994"), _T("Hudson") },
	{ _T(""), _T("Lodoss Tousenki Taikenban + Guidebook"), _T("lodossdemo"), _T(""), _T("Hudson") },
	{ _T(""), _T("Loom"), _T("loom"), _T("1992"), _T("NEC") },
	{ _T("63872abc1cf90b8a0a83c64929f64fe655c63dde"), _T("Lord of Wars"), _T("lordofwars"), _T("1991"), _T("SystemSoft") },
	{ _T("33e98e427068aca06ed3e7344aae3427864b44e4"), _T("Lords of the Rising Sun"), _T("lordsofrisingsun"), _T("1992"), _T("NEC") },
	{ _T("4f27cdb5ff71e7942cea3535d1845e820e9f6bba"), _T("Lords of Thunder"), _T("lordsofthunder"), _T("1993"), _T("Hudson") },

	{ _T(""), _T("Macross 2036"), _T("macross2036"), _T("1992"), _T("Masaya") },
	{ _T(""), _T("Macross Eternal Love Song"), _T("macrosslove"), _T("1994"), _T("Masaya") },
	{ _T(""), _T("Mad Stalker: Full Metal Force"), _T("madstalker"), _T("1994"), _T("NEC") },
	{ _T(""), _T("Madou Monogatari I: Honou no Sotsuenji"), _T("madou1"), _T("1996"), _T("Compile") },
	{ _T(""), _T("Magical Dinosaur Tour (Magical Saurus Tour)"), _T("magicalsaurus"), _T("1990"), _T("Nihon Telenet") },
	{ _T(""), _T("Magicoal"), _T("magicoal"), _T("1993"), _T("NEC") },
	{ _T(""), _T("Mahjong Clinic Special"), _T("mahjongclinic"), _T("1993"), _T("Naxat") },
	{ _T(""), _T("Mahjong Lemon Angel"), _T("lemonangel"), _T("1994"), _T("Naxat") },
	{ _T(""), _T("Mahjong On The Beach"), _T("mahjongbeach"), _T("1993"), _T("NEC Avenue") },
	{ _T(""), _T("Mahjong Sword Princess Quest Gaiden"), _T("mahjongsword"), _T("1995"), _T("Naxat") },
	{ _T(""), _T("Maho Shoujo Silky Lip"), _T("silkylip"), _T("1992"), _T("Telenet Japan") },
	{ _T(""), _T("Mamono Hunter Youko: Makai Kara no Tenkousei"), _T("youko"), _T("1992"), _T("Masaya") },
	{ _T(""), _T("Mamono Hunter Youko: Tooki Yobikoe"), _T("youko2"), _T("1992"), _T("Masaya") },
	{ _T(""), _T("The Manhole"), _T("manhole"), _T("1990"), _T("Sunsoft") },
	{ _T(""), _T("Martial Champion"), _T("martialchampion"), _T("1993"), _T("Konami") },
	{ _T(""), _T("Mashou Denki La Valeur"), _T("lavaleur"), _T("1991"), _T("Kogado") },
	{ _T(""), _T("Master Of Monsters"), _T("mastermonsters"), _T("1991"), _T("SystemSoft") },
	{ _T(""), _T("Mateki Densetsu Astralius"), _T("astralius"), _T("1991"), _T("IGS") },
	{ _T(""), _T("Megami Paradise"), _T("megamiparadise"), _T("1994"), _T("NEC") },
	{ _T(""), _T("Metal Angel"), _T("metalangel"), _T("1993"), _T("Pack-In-Video") },
	{ _T(""), _T("Metal Angel 2"), _T("metalangel2"), _T("1995"), _T("Pack-In-Video") },
	{ _T(""), _T("Metamor Jupiter"), _T("metamorjupiter"), _T("1993"), _T("NEC") },
	{ _T(""), _T("Meteor Blaster DX"), _T("meteorblaster"), _T("1994"), _T("Games Express") },
	{ _T(""), _T("Might and Magic"), _T("mightandmagic"), _T("1991"), _T("NEC Avenue") },
	{ _T(""), _T("Might and Magic III: Isles of Terra"), _T("mightmagic3"), _T("1993"), _T("Hudson") },
	{ _T(""), _T("Minesweeper"), _T("minesweeper"), _T("1992"), _T("Pack-In-Video") },
	{ _T(""), _T("Mirai Shonen Conan"), _T("miraiconan"), _T("1992"), _T("Telenet Japan") },
	{ _T(""), _T("Mitsubachi Gakuen"), _T("mitsubachi"), _T("1990"), _T("Hudson") },
	{ _T(""), _T("Monster Lair"), _T("monsterlair"), _T("1989"), _T("Hudson") },
	{ _T(""), _T("Monster Maker Yami no Ryuu Chishi"), _T("monstermaker"), _T("1994"), _T("NEC Avenue") },
	{ _T(""), _T("Moonlight Lady"), _T("moonlightlady"), _T("1993"), _T("NEC") },
	{ _T(""), _T("Moto Roader MC"), _T("motoroadermc"), _T("1992"), _T("Masaya") },
	{ _T(""), _T("Motteke Tamago"), _T("motteketamago"), _T("1997"), _T("NEC") },
	{ _T(""), _T("Mugen Senshi Valis"), _T("valis"), _T("1992"), _T("Telenet Japan") },
	{ _T(""), _T("Mystic Formula"), _T("mysticformula"), _T("1993"), _T("Micro Cabin") },

	{ _T(""), _T("Nekketsu Legend Baseball"), _T("nlegendbaseball"), _T("1995"), _T("Pack-In-Video") },
	{ _T(""), _T("Nekketsu Koukou Dodgeball Bu CD Soccer Hen"), _T("dodgeballsoccer"), _T("1991"), _T("Naxat") },
	{ _T(""), _T("Nemurenumori no Chiisana Ohanashi"), _T("nemurenumori"), _T("1993"), _T("NEC") },
	{ _T("52582651c8a6ed6e38814b72f4d7fe6836c61962"), _T("Neo Nectaris"), _T("neonectaris"), _T("1994"), _T("Hudson") },
	{ _T(""), _T("Nexzr"), _T("nexzr"), _T("1992"), _T("Naxat") },
	{ _T(""), _T("Nishimura Kyotaro Myst.: Hokutosei no Onna"), _T("nishimurakyotaro"), _T("1990"), _T("Naxat") },
	{ _T(""), _T("Nobunaga no Yabou: Bushou Fuu Roku"), _T("nobunagabushou"), _T("1993"), _T("Koei") },
	{ _T(""), _T("Nobunaga no Yabou: Zenkokuban"), _T("nobunagazenkoku"), _T("1993"), _T("Koei") },
	{ _T(""), _T("NoRiKo"), _T("noriko"), _T("1988"), _T("Hudson") },

	{ _T(""), _T("Pachiokun 3 Pachisuro & Pachinko"), _T("pachiokun3"), _T("1994"), _T("Coconuts Japan") },
	{ _T(""), _T("Pachiokun Maboroshi no Densetsu"), _T("pachiokun"), _T("1990"), _T("Coconuts Japan") },
	{ _T(""), _T("Pachiokun Warau Uchuu"), _T("pachiokunwarau"), _T("1992"), _T("Coconuts Japan") },
	{ _T(""), _T("Panic Bomber"), _T("panicbomber"), _T("1994"), _T("Hudson") },
	{ _T(""), _T("Pastel Lime"), _T("pastellime"), _T("1992"), _T("Naxat") },
	{ _T(""), _T("PC Cocoron"), _T("pccocoron"), _T("1992"), _T("NEC") },
	{ _T(""), _T("PCEngine Fan Special CD-Rom Volume 1"), _T("pcefanspecial1"), _T("1993"), _T("Tokuma Shoten") },
	{ _T(""), _T("Police Connection"), _T("policeconnection"), _T("1993"), _T("Laser Soft") },
	{ _T(""), _T("Pop'n Magic"), _T("popnmagic"), _T("1992"), _T("Telenet Japan") },
	{ _T(""), _T("Popful Mail"), _T("popfulmail"), _T("1994"), _T("NEC") },
	{ _T(""), _T("Populous"), _T("populous"), _T("1991"), _T("Hudson") },
	{ _T(""), _T("Power Golf 2 Golfer"), _T("powergolf2"), _T("1994"), _T("Hudson") },
	{ _T(""), _T("Prince of Persia"), _T("princeofpersia"), _T("1991"), _T("Riverhillsoft") },
	{ _T(""), _T("Princess Maker"), _T("princessmaker"), _T("1995"), _T("Micro Cabin") },
	{ _T(""), _T("Princess Maker 2"), _T("princessmaker2"), _T("1995"), _T("Micro Cabin") },
	{ _T(""), _T("Princess Minerva"), _T("princessminerva"), _T("1994"), _T("Riverhillsoft") },
	{ _T(""), _T("Private Eye Doll"), _T("privateeyedoll"), _T("1995"), _T("NEC") },
	{ _T(""), _T("The Pro Yakyuu"), _T("proyakyuu"), _T("1990"), _T("Intec") },
	{ _T(""), _T("The Pro Yakyuu Super '94"), _T("proyakyuu94"), _T("1994"), _T("Intec") },
	{ _T(""), _T("The Pro Yakyuu Super"), _T("proyakyuusuper"), _T("1992"), _T("Intec") },
	{ _T(""), _T("Psychic Detective Series Vol 3 AYA"), _T("psychicaya"), _T("1992"), _T("Data West") },
	{ _T(""), _T("Psychic Detective Series Vol 4 Orgel"), _T("psychicorgel"), _T("1993"), _T("Data West") },
	{ _T(""), _T("Psychic Storm"), _T("psychicstorm"), _T("1992"), _T("Laser Soft") },
	{ _T(""), _T("Puyo Puyo CD"), _T("puyopuyocd"), _T("1994"), _T("NEC Avenue") },
	{ _T(""), _T("Puyo Puyo CD Tsuu"), _T("puyopuyocd2"), _T("1996"), _T("NEC Interchannel") },

	{ _T(""), _T("Quiz Avenue"), _T("quizavenue"), _T("1990"), _T("NEC Avenue") },
	{ _T(""), _T("Quiz Avenue II"), _T("quizavenue2"), _T("1991"), _T("NEC Avenue") },
	{ _T(""), _T("Quiz Avenue III"), _T("quizavenue3"), _T("1994"), _T("NEC Avenue") },
	{ _T(""), _T("Quiz Caravan Cult Q"), _T("quizcultq"), _T("1993"), _T("Hudson") },
	{ _T(""), _T("Quiz De Gakuensai"), _T("quizgakuensai"), _T("1993"), _T("Naxat") },
	{ _T(""), _T("Quiz Donosama no Yabou"), _T("quiztonosama"), _T("1992"), _T("Hudson") },
	{ _T(""), _T("Quiz Marugoto The World"), _T("quizmarugoto"), _T("1991"), _T("Atlus") },
	{ _T(""), _T("Quiz Marugoto The World 2 Time Machine Ni Onegai!"), _T("quizmarugoto2"), _T("1992"), _T("Atlus") },
	{ _T(""), _T("Quiz no Hoshi"), _T("quiznohoshi"), _T("1992"), _T("Sunsoft") },

	{ _T(""), _T("Rainbow Islands"), _T("rainbowislands"), _T("1993"), _T("NEC Avenue") },
	{ _T(""), _T("Ranma 1/2"), _T("ranma"), _T("1990"), _T("Masaya") },
	{ _T(""), _T("Ranma 1/2: Datou, Ganso Musabetsu Kakutou-ryuu!"), _T("ranma2"), _T("1992"), _T("Masaya") },
	{ _T(""), _T("Ranma 1/2: Toraware no Hanayome"), _T("ranmatoraware"), _T("1991"), _T("Masaya") },
	{ _T("93d226059578b9c6469245e3f136d2c5bdbbd706"), _T("Rayxanber II"), _T("rayxanber2"), _T("1991"), _T("Data West") },
	{ _T("a8bbab53f95c4c92454d480e7490a1612994251e"), _T("Rayxanber III"), _T("rayxanber3"), _T("1992"), _T("Data West") },
	{ _T(""), _T("Renny Blaster"), _T("rennyblaster"), _T("1995"), _T("NEC") },
	{ _T(""), _T("Riot Zone"), _T("riotzone"), _T("1993"), _T("Hudson / Turbo Technologies") },
	{ _T(""), _T("Rising Sun"), _T("risingsun"), _T("1992"), _T("NEC") },
	{ _T("28af24d088a967e74098b775e3ab79fe631a59b6"), _T("Road Spirits"), _T("roadspirits"), _T("1991"), _T("Pack-In-Video") },
	{ _T(""), _T("Rom Rom Stadium"), _T("romromstadium"), _T("1989"), _T("NCS / Masaya") },
	{ _T(""), _T("R-Type"), _T("rtype"), _T("1991"), _T("Irem") },
	{ _T(""), _T("Ruin Kami no Isan"), _T("ruin"), _T("1993"), _T("Victor") },
	{ _T(""), _T("Ryuuko no Ken (Art of Fighting)"), _T("artoffighting"), _T("1994"), _T("Hudson") },

	{ _T(""), _T("Sangokushi III (Romance of the Three Kingdoms III)"), _T("sangokushi3"), _T("1993"), _T("Koei") },
	{ _T(""), _T("Sankokushi Eiketsu Tenka Ni Nozomu"), _T("sankokushieiketsu"), _T("1991"), _T("Naxat") },
	{ _T(""), _T("Seirei Senshi Spriggan"), _T("spriggan"), _T("1991"), _T("Naxat") },
	{ _T(""), _T("Seiryuu Densetsu Monbit"), _T("monbit"), _T("1991"), _T("Hudson") },
	{ _T(""), _T("Seisenshi Denshou Jantaku no Kisha"), _T("seisenshi"), _T("1994"), _T("Nichibutsu") },
	{ _T(""), _T("Seiya Monogatari"), _T("seiyamonogatari"), _T("1995"), _T("Hudson") },
	{ _T(""), _T("Sengoku Kantou Sankokushi"), _T("sengokukantou"), _T("1991"), _T("Intec") },
	{ _T(""), _T("Sexy Idol Mahjong"), _T("sexyidolmahjong"), _T("1993"), _T("Nichibutsu") },
	{ _T(""), _T("Sexy Idol Mahjong Fashion Monogatari"), _T("sexyidolfashion"), _T("1994"), _T("Nichibutsu") },
	{ _T(""), _T("Sexy Idol Mahjong Yakyuken no Uta"), _T("sexyidolyakyuken"), _T("1995"), _T("Nichibutsu") },
	{ _T(""), _T("Shadow of the Beast"), _T("shadowofthebeast"), _T("1992"), _T("Victor") },
	{ _T(""), _T("Shanghai II"), _T("shanghai2"), _T("1990"), _T("Hudson") },
	{ _T(""), _T("Shanghai III: Dragon's Eye"), _T("shanghai3"), _T("1992"), _T("Ask Kodansha") },
	{ _T(""), _T("Shapeshifter"), _T("shapeshifter"), _T("1992"), _T("ICOM Simulations / Turbo Technologies") },
	{ _T(""), _T("Sherlock Holmes: Consulting Detective"), _T("sherlockholmes"), _T("1991"), _T("ICOM Simulations / NEC") },
	{ _T(""), _T("Sherlock Holmes: Consulting Detective Vol. II"), _T("sherlockholmes2"), _T("1993"), _T("ICOM Simulations / Turbo Technologies") },
	{ _T(""), _T("Shiawase Usagi"), _T("shiawaseusagi"), _T("1995"), _T("NEC") },
	{ _T(""), _T("Shiawase Usagi II Torawase Usagi Sailor Z"), _T("shiawaseusagi2"), _T("1996"), _T("NEC") },
	{ _T(""), _T("Shiawase Usagi F - Yuujiyou Yorimo Aiyoku"), _T("shiawaseusagif"), _T("1997"), _T("NEC") },
	{ _T(""), _T("Shin Megami Tensei"), _T("shinmegami"), _T("1993"), _T("Atlus") },
	{ _T(""), _T("Shin Onriyou Senki"), _T("shinonryou"), _T("1995"), _T("Fujicom") },
	{ _T(""), _T("Shogi Database Giyuu"), _T("shogidatabase"), _T("1992"), _T("NEC") },
	{ _T(""), _T("Side Arms Special"), _T("sidearmsspecial"), _T("1989"), _T("NEC Avenue") },
	{ _T(""), _T("SimEarth: The Living Planet"), _T("simearth"), _T("1992"), _T("Hudson") },
	{ _T(""), _T("Slime World"), _T("slimeworld"), _T("1992"), _T("Micro World") },
	{ _T(""), _T("Slot Gambler"), _T("slotgambler"), _T("1995"), _T("Nichibutsu") },
	{ _T(""), _T("Snatcher"), _T("snatcher"), _T("1992"), _T("Konami") },
	{ _T(""), _T("Snatcher Pilot Disk"), _T("snatcherpilot"), _T("1992"), _T("Konami") },
	{ _T(""), _T("Sol Bianca"), _T("solbianca"), _T("1990"), _T("Masaya") },
	{ _T(""), _T("Sol: Moonarge"), _T("solmoonarge"), _T("1994"), _T("Irem") },
	{ _T(""), _T("Solid Force"), _T("solidforce"), _T("1995"), _T("Kogado") },
	{ _T(""), _T("Sorcerian"), _T("sorcerian"), _T("1992"), _T("Victor") },
	{ _T(""), _T("Sotsugyou Graduation"), _T("sotsugyou"), _T("1993"), _T("NEC Avenue") },
	{ _T(""), _T("Sotsugyou II Neo Generation"), _T("sotsugyou2"), _T("1994"), _T("NEC Avenue") },
	{ _T(""), _T("Sotsugyou Shashin Miki"), _T("sotsugyoushashin"), _T("1994"), _T("Coconuts Japan") },
	{ _T(""), _T("Space Fantasy Zone"), _T("spacefantasyzone"), _T("1991"), _T("NEC Avenue") },
	{ _T(""), _T("Space Invaders: The Original Game"), _T("spaceinvaders"), _T("1995"), _T("NEC Avenue") },
	{ _T(""), _T("Splash Lake"), _T("splashlake"), _T("1991"), _T("NEC Avenue") },
	{ _T("1ffa15d679e76d20c55752f4433359f534020d2d"), _T("Spriggan Mark 2: Re-Terraform Project"), _T("sprigganmark2"), _T("1992"), _T("Naxat") },
	{ _T("0d98dfbf2aae0b98b4df6cc408c9f1691250e0c4"), _T("Star Breaker"), _T("starbreaker"), _T("1994"), _T("Ray Force") },
	{ _T("a063648f74906be28462195059a2235ad4e1cea2"), _T("Star Mobile"), _T("starmobile"), _T("1992"), _T("Naxat") },
	{ _T("ec71239c6287bac0a4e5a5be76261aac4708f36d"), _T("Star Parodier"), _T("starparodier"), _T("1992"), _T("Hudson") },
	{ _T(""), _T("Startling Odyssey"), _T("startlingodyssey"), _T("1993"), _T("Ray Force") },
	{ _T(""), _T("Startling Odyssey II"), _T("startlingodyssey2"), _T("1994"), _T("Ray Force") },
	{ _T(""), _T("Steam Heart's"), _T("steamhearts"), _T("1996"), _T("TGL") },
	{ _T(""), _T("Strider Hiryuu"), _T("striderhiryuu"), _T("1994"), _T("NEC Avenue") },
	{ _T(""), _T("Sugoroku '92 Nari Tore Nariagari Trendy"), _T("sugoroku92"), _T("1992"), _T("Telenet Japan") },
	{ _T(""), _T("Summer Carnival '93 - Nexzr Special"), _T("nexzrspecial"), _T("1993"), _T("Naxat") },
	{ _T(""), _T("Super Air Zonk: Rockabilly-Paradise"), _T("superairzonk"), _T("1993"), _T("Hudson") },
	{ _T(""), _T("Super Albatross"), _T("superalbatross"), _T("1989"), _T("Shin-Nihon Laser Soft") },
	{ _T(""), _T("Super Daisenryaku"), _T("superdaisenryaku"), _T("1990"), _T("SystemSoft") },
	{ _T(""), _T("Super Darius"), _T("superdarius"), _T("1990"), _T("NEC Avenue") },
	{ _T(""), _T("Super Darius II"), _T("superdarius2"), _T("1993"), _T("NEC Avenue") },
	{ _T(""), _T("Super Mahjong Taikai"), _T("supermahjong"), _T("1992"), _T("Koei") },
	{ _T(""), _T("Super Raiden"), _T("superraiden"), _T("1992"), _T("Hudson") },
	{ _T(""), _T("Super Real Mahjong P II & III Custom"), _T("superrealmahjong23"), _T("1994"), _T("Naxat") },
	{ _T(""), _T("Super Real Mahjong P IV Custom"), _T("superrealmahjong4"), _T("1993"), _T("Naxat") },
	{ _T(""), _T("Super Real Mahjong P V Custom"), _T("superrealmahjong5"), _T("1995"), _T("Naxat") },
	{ _T(""), _T("Super Real Mahjong Special"), _T("superrealmahjong"), _T("1992"), _T("Naxat") },
	{ _T(""), _T("Super Schwartzschild"), _T("superschwart"), _T("1991"), _T("Kogado") },
	{ _T(""), _T("Super Schwartzschild 2"), _T("superschwart2"), _T("1992"), _T("Kogado") },
	{ _T(""), _T("Sword Master"), _T("swordmaster"), _T("1993"), _T("Right Stuff") },
	{ _T(""), _T("Sylphia"), _T("sylphia"), _T("1993"), _T("Tonkin House") },

	{ _T(""), _T("Tadaima Yusha Boshuuchuu"), _T("tadaimayusha"), _T("1994"), _T("Human") },
	{ _T(""), _T("Taiheiki"), _T("taiheiki"), _T("1991"), _T("Intec") },
	{ _T(""), _T("Tanjou Debut"), _T("tanjoudebut"), _T("1994"), _T("NEC Avenue") },
	{ _T(""), _T("Tecmo World Cup Super Soccer"), _T("tecmoworldcup"), _T("1992"), _T("Tecmo") },
	{ _T(""), _T("Tekipaki Working Love"), _T("tekipaki"), _T("1997"), _T("NEC") },
	{ _T(""), _T("Tenchi Muyo! Ryo-Ohki"), _T("tenchimuyo"), _T("1995"), _T("NEC Avenue") },
	{ _T(""), _T("Tenchi wo Kurau"), _T("tenchiwokurau"), _T("1994"), _T("NEC Avenue") },
	{ _T(""), _T("Tengai Makyou: Ziria"), _T("tengai1"), _T("1989"), _T("Hudson") },
	{ _T(""), _T("Tengai Makyou II: Manjimaru"), _T("tengai2"), _T("1992"), _T("Hudson") },
	{ _T(""), _T("Tengai Makyou: Fuun Kabukiden"), _T("tengaikabuki"), _T("1993"), _T("Hudson") },
	{ _T(""), _T("Tenshi no Uta"), _T("tenshino uta"), _T("1991"), _T("Telenet Japan") },
	{ _T(""), _T("Tenshi no Uta II: Datenshi no Sentaku"), _T("tenshinouta2"), _T("1993"), _T("Telenet Japan") },
	{ _T(""), _T("Terraforming"), _T("terraforming"), _T("1991"), _T("Right Stuff") },
	{ _T(""), _T("Tokimeki Memorial"), _T("tokimemorial"), _T("1994"), _T("Konami") },
	{ _T(""), _T("Top O Nerae! GunBuster Vol. 1"), _T("gunbuster1"), _T("1992"), _T("Gainax / Riverhillsoft") },
	{ _T(""), _T("Top O Nerae! GunBuster Vol. 2"), _T("gunbuster2"), _T("1993"), _T("Gainax / Riverhillsoft") },
	{ _T(""), _T("Travel Epuru"), _T("travelepuru"), _T("1992"), _T("Telenet Japan") },
	{ _T(""), _T("Travelers! Densetsu wo ButtobaSe"), _T("travelers"), _T("1994"), _T("Victor") },
	{ _T(""), _T("The TV Show"), _T("tvshow"), _T("1995"), _T("NEC") },

	{ _T(""), _T("Uchuu Senkan Yamato"), _T("yamato"), _T("1992"), _T("Human") },
	{ _T(""), _T("Ultrabox 2 Go"), _T("ultrabox2"), _T("1989"), _T("Victor") },
	{ _T(""), _T("Ultrabox 3 Go"), _T("ultrabox3"), _T("1990"), _T("Victor") },
	{ _T(""), _T("Ultrabox 4 Go"), _T("ultrabox4"), _T("1990"), _T("Victor") },
	{ _T(""), _T("Ultrabox 5 Go"), _T("ultrabox5"), _T("1991"), _T("Victor") },
	{ _T(""), _T("Ultrabox 6 Go"), _T("ultrabox6"), _T("1991"), _T("Victor") },
	{ _T(""), _T("Ultrabox Sohkan Go"), _T("ultrabox1"), _T("1989"), _T("Victor") },
	{ _T(""), _T("Urusei Yatsura: Stay With You"), _T("uruseiyatsura"), _T("1990"), _T("Hudson") },

	{ _T(""), _T("Valis II"), _T("valis2"), _T("1989"), _T("Telenet Japan") },
	{ _T(""), _T("Valis III"), _T("valis3"), _T("1990"), _T("Telenet Japan") },
	{ _T(""), _T("Valis IV"), _T("valis4"), _T("1991"), _T("Laser Soft") },
	{ _T(""), _T("Valis Visual Collection"), _T("valisvisual"), _T("1992"), _T("Telenet Japan") },
	{ _T(""), _T("Vanilla Syndrome"), _T("vanillasyndrome"), _T("1991"), _T("Nichibutsu") },
	{ _T(""), _T("Vasteel 2"), _T("vasteel2"), _T("1994"), _T("Human") },
	{ _T(""), _T("Virgin Dream"), _T("virgindream"), _T("1996"), _T("NEC") },

	{ _T(""), _T("Where in the World is Carmen Sandiego?"), _T("carmensandiego"), _T("1992"), _T("NEC") },
	{ _T(""), _T("Wizardry I & II"), _T("wizardry12"), _T("1992"), _T("Nihon Soft") },
	{ _T(""), _T("Wizardry III + IV"), _T("wizardry34"), _T("1993"), _T("Nihon Soft") },
	{ _T(""), _T("Wizardry V: Heart of The Maelstrom"), _T("wizardry5"), _T("1992"), _T("Nihon Soft") },
	{ _T(""), _T("World Heroes 2"), _T("worldheroes2"), _T("1994"), _T("Hudson") },
	{ _T(""), _T("Wrestling Angels Double Impact"), _T("wrestlingangels"), _T("1995"), _T("Human") },

	{ _T(""), _T("Xak I & II"), _T("xak12"), _T("1992"), _T("Telenet Japan") },
	{ _T(""), _T("Xak III: The Eternal Recurrence"), _T("xak3"), _T("1994"), _T("NEC Home Electronics") },

	{ _T(""), _T("Yamamura Misa Suspense: Kinsen Ka Kyo E Zara Satsu Jin Ji Ken"), _T("yamamuramisa"), _T("1992"), _T("Naxat") },
	{ _T(""), _T("Yami no Ketsuzoku Harukanaru Kioku"), _T("yaminoketsuzoku"), _T("1993"), _T("Naxat") },
	{ _T(""), _T("Yawara!"), _T("yawara"), _T("1992"), _T("Sofix") },
	{ _T(""), _T("Yawara! 2"), _T("yawara2"), _T("1994"), _T("Sofix") },
	{ _T(""), _T("Yokoyama Kouki Shin Sankokushi"), _T("yokoyamasankoku"), _T("1992"), _T("Naxat") },
	{ _T("9dc791d7c71f7b5aec03e7cd6a291586732451b5"), _T("Ys Book I & II"), _T("ys1and2"), _T("1989"), _T("Hudson") },
	{ _T(""), _T("Ys III: Wanderers from Ys"), _T("ys3"), _T("1991"), _T("Hudson") },
	{ _T(""), _T("Ys IV: The Dawn of Ys"), _T("ys4"), _T("1993"), _T("Hudson") },
	{ _T(""), _T("Yu Yu Hakusho: Yamishoubu!! Ankoku Bujutsukai"), _T("yuyuhakusho"), _T("1993"), _T("Banpresto") },

	{ _T(""), _T("Zan Kagerou no Toki"), _T("zankagerou"), _T("1991"), _T("Taito") },
	{ _T(""), _T("Zero 4 Champ II"), _T("zero4champ2"), _T("1993"), _T("Media Rings") },
	{ _T(""), _T("Zero Wing"), _T("zerowing"), _T("1992"), _T("Naxat") },
};
